name: Reusable workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World
    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.current-time }}
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet }}"
  time:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
    outputs:
      current-time: ${{ steps.time.outputs.time }}
